//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barber_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About_details
    {
        public int Id { get; set; }
        public string H3text { get; set; }
        public string Ptext { get; set; }
        public string Ultext1 { get; set; }
        public string Ultext { get; set; }
        public string Img { get; set; }
        public string H4text { get; set; }
        public string Single_Img { get; set; }
    }
}
