//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barber_Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarberShOWEntities : DbContext
    {
        public BarberShOWEntities()
            : base("name=BarberShOWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About_details> About_details { get; set; }
        public virtual DbSet<AboutCenter> AboutCenter { get; set; }
        public virtual DbSet<Appoint> Appoint { get; set; }
        public virtual DbSet<MainSlider> MainSlider { get; set; }
        public virtual DbSet<Our_Cartinca> Our_Cartinca { get; set; }
        public virtual DbSet<Our_Services> Our_Services { get; set; }
        public virtual DbSet<Working_House> Working_House { get; set; }
    }
}
