//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barber_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working_House
    {
        public int Id { get; set; }
        public string Days { get; set; }
        public string Span_Time { get; set; }
    }
}
